# SPDX-FileCopyrightText: 2023 Pôle d'Expertise de la Régulation Numérique <contact.peren@finances.gouv.fr>
#
# SPDX-License-Identifier: CC0-1.0

repos:
  - repo: local
    hooks:
    - id: black
      name: black
      entry: "./.venv/bin/black --check"
      language: system
      require_serial: true
      types_or: [python, pyi, jupyter]
    - id: flake8
      name: flake8
      entry: "./.venv/bin/flake8"
      language: system
      types_or: [python, pyi]
    # flake8-nb could be used to lint python files as well
    # but we split hooks for notebooks linting to have dedicated options
    - id: flake8-nb
      name: flake8-nb
      entry: "./.venv/bin/flake8_nb"
      language: system
      require_serial: true
      types: [jupyter]
