version: "3.8"

services:
  app:
    image: albert/tchapbot
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 .
    environment:
      - VERBOSE=true
      - SYSTEMD_LOGGING=True
      - matrix_home_server=${matrix_home_server}
      - matrix_bot_username=${matrix_bot_username}
      - matrix_bot_password=${matrix_bot_password}
      - session_path=/data/session.txt
      - groups_used=["basic", "albert"]
      - user_allowed_domains=${user_allowed_domains}
      - salt=${salt}
      - albert_api_url=${albert_api_url}
      - albert_api_token=${albert_api_token}
    ports:
      - 443:443
      - 80:80
    volumes:
      - /data/tchapbot:/data
    restart: always
