version: "3.8"

services:
  app:
    image: albert/tchapbot
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 .
    environment:
      - VERBOSE=true
      - SYSTEMD_LOGGING=True
      - matrix_home_server=${MATRIX_HOME_SERVER}
      - matrix_bot_username=${MATRIX_BOT_USERNAME}
      - matrix_bot_password=${MATRIX_BOT_PASSWORD}
      - errors_room_id=${ERRORS_ROOM_ID}
      - session_path=/data/session.txt
      - groups_used=["basic", "albert"]
      - user_allowed_domains=${USER_ALLOWED_DOMAINS}
      - salt=${SALT}
      - albert_api_url=${ALBERT_API_URL}
      - albert_api_token=${ALBERT_API_TOKEN}
      - albert_api_model_name=${ALBERT_API_MODEL_NAME}
    ports:
      - 443:443
      - 80:80
    volumes:
      - /data/tchapbot:/data
    restart: always
